spring:
  application:
    name: dfs-man

dfs:
  path: ${user.home}/dfs-man
  syncBackup: false
  autoMd5: true
  backupUrl: http://localhost:8091/upload
  downloadUrl: http://localhost:8090/download



rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: dfs-producer


server:
  port: 8090